apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: cicd
spec:
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort