apiVersion: v1
kind: Service
metadata:
  name: openproject-service
  namespace: cicd
spec:
  selector:
    app: openproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort